/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as KFromRouteImport } from './routes/k.$from'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOgCodeRouteImport } from './routes/api/og.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const KFromRoute = KFromRouteImport.update({
  id: '/k/$from',
  path: '/k/$from',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgCodeRoute = ApiOgCodeRouteImport.update({
  id: '/api/og/$code',
  path: '/api/og/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/k/$from': typeof KFromRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/$code': typeof ApiOgCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/k/$from': typeof KFromRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/$code': typeof ApiOgCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/k/$from': typeof KFromRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/$code': typeof ApiOgCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/friends'
    | '/inbox'
    | '/login'
    | '/profile'
    | '/k/$from'
    | '/api/auth/$'
    | '/api/og/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/friends'
    | '/inbox'
    | '/login'
    | '/profile'
    | '/k/$from'
    | '/api/auth/$'
    | '/api/og/$code'
  id:
    | '__root__'
    | '/'
    | '/friends'
    | '/inbox'
    | '/login'
    | '/profile'
    | '/k/$from'
    | '/api/auth/$'
    | '/api/og/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FriendsRoute: typeof FriendsRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  KFromRoute: typeof KFromRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOgCodeRoute: typeof ApiOgCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/k/$from': {
      id: '/k/$from'
      path: '/k/$from'
      fullPath: '/k/$from'
      preLoaderRoute: typeof KFromRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$code': {
      id: '/api/og/$code'
      path: '/api/og/$code'
      fullPath: '/api/og/$code'
      preLoaderRoute: typeof ApiOgCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FriendsRoute: FriendsRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  KFromRoute: KFromRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOgCodeRoute: ApiOgCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
